# Generated by Django 5.0 on 2026-02-12 07:42

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('height_stebility', models.CharField(blank=True, max_length=255, null=True)),
                ('back_support', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplicationServices.category')),
            ],
        ),
        migrations.CreateModel(
            name='ChairColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text="Enter the color name (eg. 'black' or 'white and black')", max_length=255)),
                ('color_code', models.CharField(help_text='Enter the color code in hex format', max_length=255)),
                ('color_code_2', models.CharField(blank=True, help_text='Enter the color code in hex format if its is a multicolor', max_length=255, null=True)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplicationServices.chair')),
            ],
        ),
        migrations.CreateModel(
            name='ChairImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chair_images/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplicationServices.chaircolormodel')),
            ],
        ),
    ]
