# Generated by Django 5.0 on 2026-02-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0002_category_chair_chaircolormodel_chairimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text="Enter the color name (eg. 'black' or 'white and black')", max_length=255)),
                ('color_code', models.CharField(help_text='Enter the color code in hex format', max_length=255)),
                ('color_code_2', models.CharField(blank=True, help_text='Enter the color code in hex format if its is a multicolor', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('if_discount', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplicationServices.chair')),
            ],
        ),
        migrations.AlterField(
            model_name='chairimages',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplicationServices.chaircolors'),
        ),
        migrations.DeleteModel(
            name='ChairColorModel',
        ),
    ]
