# Generated by Django 5.0 on 2026-02-12 08:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0003_chaircolors_alter_chairimages_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='key_features',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
