# Generated by Django 5.0 on 2026-02-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0004_chair_key_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaircolors',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chair_colors', to='ApplicationServices.chair'),
        ),
        migrations.AlterField(
            model_name='chairimages',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chair_images', to='ApplicationServices.chaircolors'),
        ),
    ]
