# Generated by Django 5.0 on 2026-02-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0005_alter_chaircolors_chair_alter_chairimages_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='height_stebility',
            new_name='height_stability',
        ),
    ]
