# Generated by Django 5.0 on 2026-02-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0006_rename_height_stebility_chair_height_stability'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaircolors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
