# Generated by Django 6.0.2 on 2026-02-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0007_chaircolors_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='special_tag',
            field=models.CharField(choices=[('New', 'New'), ('Bestseller', 'Bestseller'), ('Trending', 'Trending'), ('Limited', 'Limited')], default='New', max_length=255),
        ),
    ]
