# Generated by Django 6.0.2 on 2026-02-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0008_chair_special_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_landscap', models.ImageField(help_text='Image for Desktop', upload_to='landing_images/landscape/')),
                ('image_portrait', models.ImageField(help_text='Image for Mobile', upload_to='landing_images/portrait/')),
            ],
        ),
        migrations.CreateModel(
            name='ShopByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(help_text='Maximum 6 categories', max_length=6, related_name='shop_by_category', to='ApplicationServices.category')),
            ],
        ),
    ]
