# Generated by Django 6.0.2 on 2026-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationServices', '0009_landingimage_shopbycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbycategory',
            name='categories',
            field=models.ManyToManyField(help_text='Maximum 5 categories', related_name='shop_by_category', to='ApplicationServices.category'),
        ),
    ]
